### ISSUE TITLE
Profile icon is out of place

### ISSUE THREAD

**Issue by raghunandankavi2010** [vikramkakkar/SublimeNavigationView#1]
I came across your NavigationView after looking at awesome answer on stackoverflow for deckview. I have checked few other libraries on GitHub. The one by mikepenz also supports badge view check boxes and other things. I am also looking at how google inbox switches profile icons animating the same. I have looked at another library which does that. 

I used keyline pushing app from Faiz Malkani available on playstore and found that some items are out of place. They do no follow the material guidelines. I am posting a snapshot. Let me know your thoughts.

I will also take a look at the code and see if I contribute something. Thank you.

![screenshot_20160106-213805](https://cloud.githubusercontent.com/assets/4216745/12147281/1c69e3e6-b4be-11e5-9be3-1c5e297aa920.png)

**Comment by raghunandankavi2010** [comment]
The fix is remove margin from frameLayout in nav_header.xml and provide 16dp layout margins for profile icon and title. Then its aligned according to material design.
![screenshot_20160106-221122](https://cloud.githubusercontent.com/assets/4216745/12148109/ad19f120-b4c2-11e5-9a45-9d44e7d28e4c.png)

**Comment by vikramkakkar** [comment]
@raghunandankavi2010 Thanks for pointing this out! I have fixed the margins as per your suggestion, and pushed an updated apk to the play store.
