### ISSUE TITLE
Show or hide navigationview

### ISSUE THREAD

**Issue by gooodzilla** [vikramkakkar/SublimeNavigationView#15]
What method shows navigation view and what do it close?

**Comment by alashow** [comment]
See #10

**Comment by gooodzilla** [comment]
thanks, but can u exactly tell how to open it?

**Comment by alashow** [comment]
`drawerLayout.openDrawer(Gravity.LEFT);`

Change gravity if your drawer view is on different side.

**Comment by gooodzilla** [comment]
Thanks for helping, just got that there is unknown part of android, that i need to understand about drawerlayouts, actionbardrawertoogle and more. Need to understand how it work with ur libs.
Another stupid question, how to change name on nav_header programmatically, trying to findviewbyid textview, getting null pointer exception on setText, but it is not null 100%. May be there is some functions to change it? Big thanks!

**Comment by vikramkakkar** [comment]
> ... how to change name on nav_header programmatically

Verify if the `TextView` _is_ indeed a part of your view hierarchy. You can do this in a few different ways. Easiest would be to comment the call to `setText(...)` and adding `android:text="TESTING"` to your `TextView's` xml definition. 

If the text is shown in your nav header, you are calling `findViewById()` on the wrong `View`. If you're inside an `Activity`, `Activity#findViewById(int)` will not return null after `Activity#setContentView(...)` has been called. If you are using a `View` to find the `TextView`, for instance `myView.findViewById(int)`, check if `myView` is a parent/ancestor of the `TextView`. 

Perhaps, the easiest way to get hold of the `TextView` is to grab the header view from `SublimeNavigationView` and call `findViewById` on it:

```
TextView myTextView = (TextView) (mSublimeNavigationView.getHeaderView()).findViewById(R.id.my_text_view_id);

// set new text
myTextView.setText("....");
```

Else, show us your code and we might be able to spot the problem.

**Comment by gooodzilla** [comment]
Thanks for helping for everyone, all problems was done. Thanks a lot, plus t u all:)
