### ISSUE TITLE
Open group intent when group, expand/collapse when clicked arrow

### ISSUE THREAD

**Issue by alashow** [vikramkakkar/SublimeNavigationView#2]
Is it possible to open intent (or whatever in clickListener) when group is clicked, and  expand/collapse group only when clicked arrow?

**Comment by vikramkakkar** [comment]
Not at the moment. 

I'll see if I can add this functionality. But, it'll probably happen sometime next week since I'm quite busy at the moment. Will keep you posted.

**Comment by vikramkakkar** [comment]
I just finished implementing this feature.

**Usage:**

Following method added to `SublimeMenu` does the trick:

```
// Controls whether a click on Group Header expands/collapses the group, or
// sends the `GROUP_HEADER_CLICKED` event. If set to `true`, the group 
// only expands/collpases when the chevron is clicked.
public void expandCollapseGroupOnlyOnChevronClick(boolean restrict)
```

By default, the behaviour is as before: clicking anywhere inside the Group Header triggers expand/collapse action. If the above-mentioned method is called with `true`, clicking on the Group Header (but not the chevron) does two things in the following order:
1. It calls the supplied `OnNavigationMenuEventListener` callback with `OnNavigationMenuEventListener.Event.GROUP_HEADER_CLICKED`. _If you return `true` from this callback, no further action is taken._
2. If you return `false` from the callback, `SublimeMenu` checks if an `Intent` is set on the Group Header. _The `Intent` will not be checked for (or fired) if you return `true` from the callback._

**Comment by alashow** [comment]
Thank you!

A few questions. I don't use/set intents to menu items. I just save id's of created menuItems, and know which object is clicked. So I think I can use same thing with groupHeaderItem and return false?

**Comment by vikramkakkar** [comment]
> I don't use/set intents to menu items. I just save id's of created menuItems, and know which object is clicked.

That's fine.

> So I think I can use same thing with groupHeaderItem and return false?

First of all, the click on the Group Header (but not the arrow) will send `OnNavigationMenuEventListener.Event.GROUP_HEADER_CLICKED`. So, your callback should look like:

```
// set listener to get notified of menu events
snv.setNavigationMenuEventListener(new OnNavigationMenuEventListener() {
    @Override
    public boolean onNavigationMenuEvent(OnNavigationMenuEventListener.Event event, SublimeBaseMenuItem menuItem) {
        switch (event) {
            ........
            ........
            case GROUP_EXPANDED:
                // called when the chevron (arrow) is clicked if group is in expanded state 
                return true;
            case GROUP_COLLAPSED:
                // called when the chevron (arrow) is clicked if group is in collapsed state 
                return true;
            case GROUP_HEADER_CLICKED:
                // called when Group Header is clicked. 
                // If you are not setting an intent, it does not matter if you return `true` or `false`. 
                // The important thing to note is that the click event will be delivered under
                // GROUP_HEADER_CLICKED - not the `default` below which 
                // handles CLICKED events. 

                // I think this is what you are doing
                if (menuItem.getItemId() == somePresavedID) {
                    // launch intent
                    return true;
                }
                return false;
            default: // OnNavigationMenuEventListener.Event.CLICKED
                // handle click event
                return true;
            }
            return false;
        }
    });
```

Basically, return `true` if you have handled the `event`. Otherwise, return `false`. In your case, you are handling the `event` by checking against the previously saved IDs, and then firing an intent if a match is found. So, if a match is found, return `true`, else return `false`.

I hope this is clear.

**Comment by alashow** [comment]
Yeah, i got it :) Thanks!

I couldn't get latest dev-snapshot build from jitpack. Latest build on jitpack is "custom divider color" commit. (https://jitpack.io/#vikramkakkar/SublimeNavigationView). Could you please upload last commit too?

**Comment by vikramkakkar** [comment]
I'm not sure why Jitpack did not pick on the latest commit since its been published for 17 hours now. Looks like its available now:

```
compile 'com.github.vikramkakkar:SublimeNavigationView:dev-df7ecdadaa-1'
```

You can also use:

```
apply plugin: 'com.android.application'

// This will fetch the latest commit from github repo 
configurations.all {
    resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    ....
    ....

    buildTypes {
        release {
            ....
        }
    }
}

dependencies {
    ....
    compile group: "com.github.vikramkakkar", name: "SublimeNavigationView", version: "dev-SNAPSHOT", changing: true
}
```

Lastly, to check if you are working with the latest commit, look at the log:

```
I/SublimeNavigationView: Current library debug version: 3
```

This should correspond to [Config.DEBUG_VERSION](https://github.com/vikramkakkar/SublimeNavigationView/blob/dev/sublimenavigationviewlibrary/src/main/java/com/appeaser/sublimenavigationviewlibrary/Config.java#L22):

```
public class Config {
    ....
    public static final int DEBUG_VERSION = 3;
}
```

**Comment by alashow** [comment]
thanks, i appreciate your help!
