### ISSUE TITLE
Menu margins missing before API 20

### ISSUE THREAD

**Issue by danbrough** [vikramkakkar/SublimeNavigationView#22]
Trying to work out why the left and right margins in the menu disappear on versions less than android 5.1 (or perhaps 5.0).

![screenshot_2016-11-08_22-25-04](https://cloud.githubusercontent.com/assets/2946482/20093724/ca63f898-a602-11e6-9876-d775d4a6f6eb.png)

Thats API:16 on the left and API:22 on the right.

**Comment by danbrough** [comment]
The nav menu header looks fine.

**Comment by alashow** [comment]
See this #11 
Dev branch contains some fixes, including to this one. See [here](https://github.com/vikramkakkar/SublimeNavigationView/issues/8#issuecomment-182754088) for how to use latest snapshot.

**Comment by danbrough** [comment]
Awesome!. Thanks for that. I didn't notice there was a dev branch.
I'll give that a try.
